name: Python Calculator CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-calculator:
    runs-on: ubuntu-latest # Single OS (you can change this to windows-latest or macos-latest if needed)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Single Python version (you can change this to 3.8 or 3.9 if needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run calculator tests
        run: |
          echo "Running tests for Python 3.10 on Ubuntu"
          pytest --junitxml=test-results/results.xml

      - name: Upload test results
        if: always() # Ensures artifacts are uploaded even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/results.xml
